name: Generate SDK Action
description: Generate an SDK using the OpenAPI Generator Project
inputs: 
  branch-name: 
    description: Branch name
    required: true
  token: 
    description: Github auth token
    required: true
  language: 
    description: The generator name (language) (`-g`) argument for the openapi-generator-cli
    required: true
  config:
    description: The configuration (`-c`) argument for the openapi-generator-cli
    required: true
  user-email: 
    description: Git user email
    default: dx@bandwidth.com
    required: false
  username: 
    description: Github username
    default: DX-Bandwidth
    required: false
  openapi-generator-version: 
    description: The OpenAPI Generator project version, in `x.x.x` format
    required: false
    default: '6.6.0'
  api-spec-path: 
    description: The destination of the API Specification to generate a client from
    required: false
    default: ./bandwidth.yml

outputs: 
  changes: 
    description: Boolean representing if files in the SDK were changed or not.
    value: ${{ steps.commit.outputs.changes }}

runs: 
  using: composite
  steps: 
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Configure Git and Create Branch
      run: |
          git config user.email ${{ inputs.user-email }}
          git config user.name ${{ inputs.username }}
          git checkout -b ${{ inputs.branch-name }}
      shell: bash

    - name: Setup OpenAPI Generator CLI
      run: |
        npm install @openapitools/openapi-generator-cli -g
        openapi-generator-cli version-manager set ${{ inputs.openapi-generator-version }}
      shell: bash

    - name: Build SDK
      run: |
        openapi-generator-cli generate \
        -g ${{ inputs.language }} \
        -i ${{ inputs.api-spec-path }} \
        -c ${{ inputs.config }} \
        -o ./
      shell: bash

    - name: Commit if Necessary
      id: commit
      run: |
        if git diff --quiet; then
          echo "No Changes"
        else
          git add .
          git commit -m "Generate SDK with OpenAPI Generator Version ${{ inputs.openapi-generator-version }}"
          # git push origin ${{ inputs.branch-name }}
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
