---
inputs:
- inputFile: "./api-specs/messaging.json"
- inputFile: "./api-specs/voice.json"
- inputFile: "./api-specs/multiFactorAuth.json"
- inputFile: "./api-specs/phoneNumberLookup.json"
- inputFile: "./api-specs/webrtc.json"
# - inputFile: "./api-specs/dash.json"
# - inputFile: "./api-specs/dashNotifications.json"

# - inputFile: "./jira.swagger.json"
#   pathModification:
#     stripStart: "/rest"
#     prepend: "/jira"
#   operationSelection:
#     includeTags:
#     - included
#   description:
#     append: true
# - inputFile: "./confluence.swagger.yaml"
#   dispute:
#     prefix: Confluence
#   pathModification:
#     prepend: "/confluence"
#   operationSelection:
#     excludeTags:
#     - excluded
output: "./bandwidth.json"
