name: Test
on:
  pull_request:
    paths:
      - "action.yml"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test with Local Files
        uses: ./
        with:
          language: python
          api-spec-path: ./utils/bandwidth.yml
          config: ./utils/test-config.yml
