name: Test
on:
  pull_request:
    paths:
      - "action.yml"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test with Local Files
        id: generate
        uses: ./
        with:
          branch-name: ci-cd-test
          username: ${{ secrets.DX_GITHUB_USERNAME }}
          token: ${{ secrets.DX_GITHUB_TOKEN }}
          openapi-generator-version: 6.5.0
          language: python
          api-spec-path: ./utils/bandwidth.yml
          config: ./utils/test-config.yml

      - name: Delete Branch
        if: ${{ always() }}
        run: git push origin --delete ci-cd-test
        shell: bash
