name: Test
on:
  pull_request:
    paths:
      - "action.yml"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ fromJSON(vars.SWI_GLORG_UBUNTU_2204) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get Github and Jira Tokens from Vault
        uses: Bandwidth/vault-provider-action@v1
        with:
          secrets: |
            workloads/prod/software_infra::secrets:dx-github-token:dx-github-token::DX_GITHUB_TOKEN

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test with Local Files
        id: generate
        uses: ./
        with:
          branch-name: ci-cd-test
          token: ${{ env.DX_GITHUB_TOKEN }}
          openapi-generator-version: 6.5.0
          language: python
          api-spec-path: ./utils/bandwidth.yml
          config: ./utils/test-config.yml

      - name: Delete Branch
        if: ${{ always() }}
        run: git push origin --delete ci-cd-test
        shell: bash
